name: Yutaura/actions/action-release-changeset
author: Yutaura
description: A GitHub Action to release changesets

inputs:
  cwd:
    description: The working directory to run the action in
    required: false
    default: .
  commit-message:
    description: The commit message to use when committing the changeset
    required: false
  pr-title:
    description: The title of the pull request
    required: false
  token:
    description: The GitHub token to use for authentication
    required: true
  setup-git-user:
    description: Whether to set up the git user
    required: false
    default: "true"
  auto-merge:
    description: Whether to automatically merge the pull request
    required: false
    default: "false"
  pre-tag-script:
    description: A script to run before tagging the release
    required: false

outputs:
  pr-number:
    description: The number of the pull request that was created
  published:
    description: Whether the changeset was published

runs:
  using: node20
  main: dist/main.js
