name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: ./.github/actions/setup
        with:
          token: ${{ steps.app-token.outputs.token }}
          bot-app-slug: ${{ steps.app-token.outputs.app-slug }}

      - run: pnpm install
      - run: pnpm check
      - run: pnpm test

      - uses: int128/update-generated-files-action@6ac8557861efc7d8c34f4e3f182f9c39b26e6e76 # v2.53.0
        with:
          token: ${{ steps.app-token.outputs.token }}
